base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('categories.urls')),
]

category/urls.py
# urls.py
from django.urls import path
from .views import add_categories,get_categories,delete_all



app_name='category'
urlpatterns = [
    path("", get_categories, name="get_categories"),
    path("add/", add_categories, name="add_categories"),
    path('delete-all/', delete_all, name='delete_all'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('category.urls',namespace='category')),
]

digi_say/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static  import static


urlpatterns = []

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))]


urlpatterns += [
    path('admin/', admin.site.urls),
    path('', include('sw_task.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

categories/models.py
from typing import Any
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)

    def __str__(self):
        return "Category: " + str(self.id) + " Parent: " + str(self.parent_id) if self.parent_id else "Root Category"
    

categories/models/Category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=1000)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

category/models.py
from django.db import models
from autoslug import AutoSlugField
from mptt.models import MPTTModel,TreeForeignKey
# Create your models here.






class Category(MPTTModel):
    parent = TreeForeignKey('self', related_name='children', on_delete=models.CASCADE, blank = 
    True, null=True)
    title = models.CharField(max_length=100) 
    slug = AutoSlugField(populate_from='title', unique=True, null=False, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    level=models.IntegerField()
    is_checked = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        if self.parent is None:
            self.level=1
            
        elif self.parent.title.count('SUB ') == 0:
            
            self.level=self.parent.level+1
            
        else:
            
            self.level=self.parent.level+1
            
        super().save(*args, **kwargs)
        return self.level

        


            
    
    def __str__(self):
        return self.title

    class MPTTMeta:
        
        order_insertion_by=['created_at']
 
       
       
        unique_together = ('slug', 'parent',)    
        verbose_name_plural = "categories"     

 

categories/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse
from .models import Category
from .utils import get_adjacency_list, create_default_categories, create_sub_categories, check_if_child_exists, get_categories

class CategoryView(View):
    def get(self, request):
        """
        first time, it will render the home page and then 
        it will return the adjacency list of all categories in the database to construct the tree.
        """
        if request.headers.get('Content-Type') == 'application/json':
            categories = get_categories()
            return JsonResponse(get_adjacency_list(categories))
        else:
            return render(request, 'home.html')



    def post(self, request):
        """
        1- know the current parent
        2- check if it has children already
        3- if it has children, return a message that it has already been clicked
        4- if it doesn't have children, create two sub categories and return them
        """
        parent_id = request.POST.get('parent')
        child_exists = check_if_child_exists(parent_id)
        if child_exists:
            return JsonResponse({"status": "already clicked"})

        subcategories = create_sub_categories(parent_id)
        subcategories = [{"id": subcategory.id, "name": subcategory.name} for subcategory in subcategories]
        
        return JsonResponse({"status": "success", "subcategories": subcategories})



    def delete(self, request):
        """
        Deletes all categories in the database and creates two default categories.
        """
        try:
            Category.objects.all().delete()
            create_default_categories()
            return JsonResponse({'success': True})
        except:
            return JsonResponse({'success': False})

categories/views/category.py
from django.http import JsonResponse
from django.shortcuts import render
from categories.models import Category
from django.core.exceptions import ObjectDoesNotExist


def category_selection_view(request):
    return render(request, 'categories/categories.html')


def get_subcategories(request, category_id):
    try:
        parent_category = Category.objects.get(id=category_id)
    except ObjectDoesNotExist:
        return JsonResponse({'error': 'Parent category does not exist'}, status=400)

    subcategories = Category.objects.filter(parent=parent_category)

    if subcategories.exists():
        data = [{'id': sub.id, 'name': sub.name} for sub in subcategories]
    else:
        data = create_subcategories(parent_category)

    return JsonResponse(data, safe=False)


def create_subcategories(parent_category):
    subcategory_names = [f'SUB {parent_category.name} - 1', f'SUB {parent_category.name} - 2']

    created_subcategories = []
    for subcategory_name in subcategory_names:
        subcategory = Category.objects.create(name=subcategory_name, parent=parent_category)
        created_subcategories.append({'id': subcategory.id, 'name': subcategory.name})

    return created_subcategories

category/views.py
# Import the necessary modules

from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Category
# Create your views here.



def delete_all(request):
    """ this method is used to delete the whole data inside database to reset """
    Category.objects.all().delete()
    return redirect('/')

def create_categories():
    """ this method is used to create the two parent categories ."""
    # Check if categories already exist
    if Category.objects.count() == 0:
    # Create two categories
        category1 = Category.objects.create(title='Category A')
        category2 = Category.objects.create(title='Category B')
        # print(category1,category2)
    

def get_categories(request):
    """ used to fetch the whole data and then render it on the html file , to make sure there is always two parent categories 
    i used a callback function to create the categories of two parent if not exist. """
    
    # Call the function to create categories
    create_categories()

    # # Get all the categories from the database
    categories = Category.objects.all()
    print(categories)

    # Render the template with the categories
    return render(request, 'index.html', {'categories': categories})




    



def add_categories(request):
    
    """used to add new two categories depend on the checked category (parent) """
    
    if request.method == 'POST':
        
        # Get the category values from the POST data
        category_id = request.POST.get('id')
        # Get the title of the parent category using id
        category = Category.objects.get(id=category_id)
        category_title = category.title
        
        is_checked = request.POST.get('is_checked')
        
        print(f'id: {category_id}, is_checked: {is_checked}')
        

        
        
        parent_id = category_id
        parent_level=request.POST.get("parent_level")
            
        if category_title .count('SUB ') == 0  :
            category1 = "SUB " + category_title + '1'
            print(category1)
            category2 = "SUB " + category_title + '2'
            print(category2)
            # Get the parent category from the database
            parent_category = Category.objects.get(id=parent_id)
            # Create two new categories with parent_category as their parent and save them to the database
            new_category1 = Category(title=category1, parent=parent_category,level=parent_level)
            new_category2 = Category(title=category2, parent=parent_category,level=parent_level)
            new_category1.save()
            new_category2.save()
            get_categories(request)
            return JsonResponse({'message': 'success'})
            
            
        else:
            category1  ="SUB " + category_title+ '-1'
            category2  ="SUB " + category_title+ '-2'
            
            # Get the parent category from the database
            parent_category = Category.objects.get(id=parent_id)
            # Create two new categories with parent_category as their parent and save them to the database
            new_category1 = Category(title=category1, parent=parent_category,level=parent_level)
            new_category2 = Category(title=category2, parent=parent_category,level=parent_level)
            new_category1.save()
            new_category2.save()
            get_categories(request)
            return JsonResponse({'message': 'success'})
    else:
        # Return an error response
        return JsonResponse({"status": "error"})

category/templates/category/index.html
<!-- my_template.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>My Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'jquery-3.7.1.min.js' %}"></script>
    

    <script>


        $(document).ready(function() {

            

    
        
            // When a checkbox is clicked
            $("input[type='checkbox']").click(function(e) {
               
              
          
              // Check if the checkbox is checked
              if ($(this).is(":checked")) {
                // Get the ID of the category
                var categoryId = $(this).attr("name");
                
                // Send an AJAX request to add the category to the database
                $.ajax({
                  url: "add/",
                  type: "POST",
                  data: {
                    id: categoryId,
                    is_checked: true,
                    
                    
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                  },
                  success: function(response) {
                  
                  },
                  error: function(response) {
                    alert("Error adding category!");
                  }
                  
                });

                
                
              }
              
            });
          });
          
    </script>
</head>
<body class="m-5">
    <h1>Categories Task</h1>
    <div class="m-5 text-center" >
<button class="mr-2" > <a class=" mr-2" id="a_style"style="text-decoration: none; color: black;"href="{% url 'category:delete_all' %}">Reset</a></button>
    <button onclick="window.location.reload()" style="margin-left: 30px; ">Reload Page</button>
    </div>

    <form id="myForm" class="form-group" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        
          {% load mptt_tags %}
          
        <ul id="category-list"class="no-bullets form-control">
          {% recursetree categories %} 
          <li class="form-text text-muted"><input type="checkbox" name="{{ node.id }}" {% if node.is_checked %}checked{% endif %}>{{ node.title }}</li>
            {% if not node.is_leaf_node %}
            <ul id="category-list"class="children no-bullets   p1-md-5">
            {{ children }}
          </ul>
           

            {% endif %}
          {% endrecursetree  %} 
{% comment %}          
             {% for category in categories %}
              <li><input type="checkbox" name="{{ category.id }}" {% if category.is_checked %}checked{% endif %}>{{ category.title }}</li>
            {% endfor %}  {% endcomment %}
          
          </ul> 
       
    </form>
</body>
</html>